channels:
     - conda-forge
dependencies:
     - dlib
     - numpy
     - scipy
     - opencv
     - imutils==0.5.4
     - keras==2.8.0
     - Pillow==9.1.0
     - scikit-learn
     - streamlit==1.9.0
     - tensorflow
     - tqdm==4.62.3
